{
  "chart": {
    "reflow": true
  },
  "title": {
    "text": "All employees"
  },
  "yAxis": {
    "title": "",
    "type": "linear",
    "labels": {
      "format": "£{value: ,f}"
    }
  },
  "credits": {
    "enabled": false
  },
  "exporting": {
    "enabled": false
  },
  "boost": {
    "enabled": false
  },
  "plotOptions": {
    "series": {
      "label": {
        "enabled": false
      },
      "turboThreshold": 0,
      "showInLegend": true,
      "marker": {
        "enabled": false
      }
    },
    "treemap": {
      "layoutAlgorithm": "squarified"
    },
    "scatter": {
      "marker": {
        "symbol": "circle"
      }
    }
  },
  "series": [
    {
      "name": "England",
      "data": [
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 331.2,
          "Lower": 329.9017,
          "Upper": 332.4983,
          "x": 1017619200000,
          "y": 331.2
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 342.6,
          "Lower": 340.5855,
          "Upper": 344.6145,
          "x": 1049155200000,
          "y": 342.6
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 353.2,
          "Lower": 351.1232,
          "Upper": 355.2768,
          "x": 1080777600000,
          "y": 353.2
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 356.7,
          "Lower": 354.6026,
          "Upper": 358.7974,
          "x": 1112313600000,
          "y": 356.7
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 368.9,
          "Lower": 367.4539,
          "Upper": 370.3461,
          "x": 1143849600000,
          "y": 368.9
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 382.9,
          "Lower": 381.399,
          "Upper": 384.401,
          "x": 1175385600000,
          "y": 382.9
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 396.1,
          "Lower": 394.5473,
          "Upper": 397.6527,
          "x": 1207008000000,
          "y": 396.1
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 402.9,
          "Lower": 401.3206,
          "Upper": 404.4794,
          "x": 1238544000000,
          "y": 402.9
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 411.1,
          "Lower": 409.4885,
          "Upper": 412.7115,
          "x": 1270080000000,
          "y": 411.1
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 405.6,
          "Lower": 403.2151,
          "Upper": 407.9849,
          "x": 1301616000000,
          "y": 405.6
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 412.4,
          "Lower": 410.7834,
          "Upper": 414.0166,
          "x": 1333238400000,
          "y": 412.4
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 421.4,
          "Lower": 419.7481,
          "Upper": 423.0519,
          "x": 1364774400000,
          "y": 421.4
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 421.6,
          "Lower": 420.7737,
          "Upper": 422.4263,
          "x": 1396310400000,
          "y": 421.6
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 429,
          "Lower": 426.4775,
          "Upper": 431.5225,
          "x": 1427846400000,
          "y": 429
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 442.1,
          "Lower": 440.367,
          "Upper": 443.833,
          "x": 1459468800000,
          "y": 442.1
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 453.9,
          "Lower": 451.2311,
          "Upper": 456.5689,
          "x": 1491004800000,
          "y": 453.9
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 465.7,
          "Lower": 462.9617,
          "Upper": 468.4383,
          "x": 1522540800000,
          "y": 465.7
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 483,
          "Lower": 480.16,
          "Upper": 485.84,
          "x": 1554076800000,
          "y": 483
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 484.3,
          "Lower": 481.4523,
          "Upper": 487.1477,
          "x": 1585699200000,
          "y": 484.3
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 510,
          "Lower": 508.0008,
          "Upper": 511.9992,
          "x": 1617235200000,
          "y": 510
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 536.6,
          "Lower": 535.5483,
          "Upper": 537.6517,
          "x": 1648771200000,
          "y": 536.6
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 576.9,
          "Lower": 574.6386,
          "Upper": 579.1614,
          "x": 1680307200000,
          "y": 576.9
        }
      ],
      "type": "line",
      "id": "England"
    },
    {
      "name": "Northern Ireland",
      "data": [
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 284.3,
          "Lower": 273.7127,
          "Upper": 294.8873,
          "x": 1017619200000,
          "y": 284.3
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 290,
          "Lower": 279.2004,
          "Upper": 300.7996,
          "x": 1049155200000,
          "y": 290
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 305.4,
          "Lower": 292.8297,
          "Upper": 317.9703,
          "x": 1080777600000,
          "y": 305.4
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 318.7,
          "Lower": 307.4563,
          "Upper": 329.9437,
          "x": 1112313600000,
          "y": 318.7
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 322.8,
          "Lower": 310.7789,
          "Upper": 334.8211,
          "x": 1143849600000,
          "y": 322.8
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 329.6,
          "Lower": 317.9717,
          "Upper": 341.2283,
          "x": 1175385600000,
          "y": 329.6
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 345,
          "Lower": 332.8284,
          "Upper": 357.1716,
          "x": 1207008000000,
          "y": 345
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 354.6,
          "Lower": 342.0897,
          "Upper": 367.1103,
          "x": 1238544000000,
          "y": 354.6
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 354.4,
          "Lower": 342.5914,
          "Upper": 366.2086,
          "x": 1270080000000,
          "y": 354.4
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 354.6,
          "Lower": 342.7847,
          "Upper": 366.4153,
          "x": 1301616000000,
          "y": 354.6
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 360.1,
          "Lower": 348.1015,
          "Upper": 372.0985,
          "x": 1333238400000,
          "y": 360.1
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 365.2,
          "Lower": 353.7473,
          "Upper": 376.6527,
          "x": 1364774400000,
          "y": 365.2
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 363.1,
          "Lower": 351.0015,
          "Upper": 375.1985,
          "x": 1396310400000,
          "y": 363.1
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 381.7,
          "Lower": 368.9818,
          "Upper": 394.4182,
          "x": 1427846400000,
          "y": 381.7
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 392.5,
          "Lower": 380.1912,
          "Upper": 404.8088,
          "x": 1459468800000,
          "y": 392.5
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 407.4,
          "Lower": 393.8254,
          "Upper": 420.9746,
          "x": 1491004800000,
          "y": 407.4
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 420.2,
          "Lower": 406.1989,
          "Upper": 434.2011,
          "x": 1522540800000,
          "y": 420.2
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 429.3,
          "Lower": 417.52,
          "Upper": 441.08,
          "x": 1554076800000,
          "y": 429.3
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 432.7,
          "Lower": 419.1305,
          "Upper": 446.2695,
          "x": 1585699200000,
          "y": 432.7
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 469.5,
          "Lower": 458.4574,
          "Upper": 480.5426,
          "x": 1617235200000,
          "y": 469.5
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 499.2,
          "Lower": 488.4372,
          "Upper": 509.9628,
          "x": 1648771200000,
          "y": 499.2
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 533,
          "Lower": 520.4638,
          "Upper": 545.5362,
          "x": 1680307200000,
          "y": 533
        }
      ],
      "type": "line",
      "id": "Northern Ireland"
    },
    {
      "name": "Scotland",
      "data": [
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 302,
          "Lower": 296.0808,
          "Upper": 307.9192,
          "x": 1017619200000,
          "y": 302
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 316.5,
          "Lower": 310.2966,
          "Upper": 322.7034,
          "x": 1049155200000,
          "y": 316.5
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 323.7,
          "Lower": 316.721,
          "Upper": 330.679,
          "x": 1080777600000,
          "y": 323.7
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 333.4,
          "Lower": 326.8654,
          "Upper": 339.9346,
          "x": 1112313600000,
          "y": 333.4
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 345.5,
          "Lower": 339.4054,
          "Upper": 351.5946,
          "x": 1143849600000,
          "y": 345.5
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 360.2,
          "Lower": 353.1401,
          "Upper": 367.2599,
          "x": 1175385600000,
          "y": 360.2
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 377.2,
          "Lower": 370.5462,
          "Upper": 383.8538,
          "x": 1207008000000,
          "y": 377.2
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 386.4,
          "Lower": 379.5839,
          "Upper": 393.2161,
          "x": 1238544000000,
          "y": 386.4
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 393.3,
          "Lower": 385.5913,
          "Upper": 401.0087,
          "x": 1270080000000,
          "y": 393.3
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 392.7,
          "Lower": 385.0031,
          "Upper": 400.3969,
          "x": 1301616000000,
          "y": 392.7
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 395.9,
          "Lower": 389.6923,
          "Upper": 402.1077,
          "x": 1333238400000,
          "y": 395.9
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 409.3,
          "Lower": 402.0799,
          "Upper": 416.5201,
          "x": 1364774400000,
          "y": 409.3
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 413.7,
          "Lower": 405.5915,
          "Upper": 421.8085,
          "x": 1396310400000,
          "y": 413.7
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 423.6,
          "Lower": 416.1277,
          "Upper": 431.0723,
          "x": 1427846400000,
          "y": 423.6
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 433.2,
          "Lower": 425.5584,
          "Upper": 440.8416,
          "x": 1459468800000,
          "y": 433.2
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 441.4,
          "Lower": 434.4788,
          "Upper": 448.3212,
          "x": 1491004800000,
          "y": 441.4
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 452.6,
          "Lower": 444.6161,
          "Upper": 460.5839,
          "x": 1522540800000,
          "y": 452.6
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 472.8,
          "Lower": 465.3865,
          "Upper": 480.2135,
          "x": 1554076800000,
          "y": 472.8
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 487,
          "Lower": 478.4093,
          "Upper": 495.5907,
          "x": 1585699200000,
          "y": 487
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 504.7,
          "Lower": 495.7971,
          "Upper": 513.6029,
          "x": 1617235200000,
          "y": 504.7
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 528.6,
          "Lower": 520.3116,
          "Upper": 536.8884,
          "x": 1648771200000,
          "y": 528.6
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 588,
          "Lower": 575.3227,
          "Upper": 600.6773,
          "x": 1680307200000,
          "y": 588
        }
      ],
      "type": "line",
      "id": "Scotland"
    },
    {
      "name": "Wales",
      "data": [
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 290.5,
          "Lower": 281.3899,
          "Upper": 299.6101,
          "x": 1017619200000,
          "y": 290.5
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 300.3,
          "Lower": 292.0598,
          "Upper": 308.5402,
          "x": 1049155200000,
          "y": 300.3
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 317,
          "Lower": 307.6802,
          "Upper": 326.3198,
          "x": 1080777600000,
          "y": 317
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 320.6,
          "Lower": 311.8027,
          "Upper": 329.3973,
          "x": 1112313600000,
          "y": 320.6
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 334.5,
          "Lower": 325.3213,
          "Upper": 343.6787,
          "x": 1143849600000,
          "y": 334.5
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 337.5,
          "Lower": 328.239,
          "Upper": 346.761,
          "x": 1175385600000,
          "y": 337.5
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 347.6,
          "Lower": 338.0619,
          "Upper": 357.1381,
          "x": 1207008000000,
          "y": 347.6
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 361.4,
          "Lower": 352.1915,
          "Upper": 370.6085,
          "x": 1238544000000,
          "y": 361.4
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 369.1,
          "Lower": 358.2485,
          "Upper": 379.9515,
          "x": 1270080000000,
          "y": 369.1
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 366.5,
          "Lower": 357.8799,
          "Upper": 375.1201,
          "x": 1301616000000,
          "y": 366.5
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 366.5,
          "Lower": 357.8799,
          "Upper": 375.1201,
          "x": 1333238400000,
          "y": 366.5
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 381.1,
          "Lower": 369.1487,
          "Upper": 393.0513,
          "x": 1364774400000,
          "y": 381.1
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 383.3,
          "Lower": 372.7822,
          "Upper": 393.8178,
          "x": 1396310400000,
          "y": 383.3
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 388.1,
          "Lower": 378.2112,
          "Upper": 397.9888,
          "x": 1427846400000,
          "y": 388.1
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 408,
          "Lower": 398.4038,
          "Upper": 417.5962,
          "x": 1459468800000,
          "y": 408
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 412.1,
          "Lower": 402.4074,
          "Upper": 421.7926,
          "x": 1491004800000,
          "y": 412.1
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 422.5,
          "Lower": 411.7347,
          "Upper": 433.2653,
          "x": 1522540800000,
          "y": 422.5
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 446.2,
          "Lower": 436.5799,
          "Upper": 455.8201,
          "x": 1554076800000,
          "y": 446.2
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 455.1,
          "Lower": 442.6121,
          "Upper": 467.5879,
          "x": 1585699200000,
          "y": 455.1
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 470.4,
          "Lower": 461.1802,
          "Upper": 479.6198,
          "x": 1617235200000,
          "y": 470.4
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 505.9,
          "Lower": 494.9928,
          "Upper": 516.8072,
          "x": 1648771200000,
          "y": 505.9
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 540,
          "Lower": 527.2992,
          "Upper": 552.7008,
          "x": 1680307200000,
          "y": 540
        }
      ],
      "type": "line",
      "id": "Wales"
    },
    {
      "name": "England",
      "data": [
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 331.2,
          "Lower": 329.9017,
          "Upper": 332.4983,
          "x": 1017619200000,
          "low": 329.9017,
          "high": 332.4983
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 342.6,
          "Lower": 340.5855,
          "Upper": 344.6145,
          "x": 1049155200000,
          "low": 340.5855,
          "high": 344.6145
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 353.2,
          "Lower": 351.1232,
          "Upper": 355.2768,
          "x": 1080777600000,
          "low": 351.1232,
          "high": 355.2768
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 356.7,
          "Lower": 354.6026,
          "Upper": 358.7974,
          "x": 1112313600000,
          "low": 354.6026,
          "high": 358.7974
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 368.9,
          "Lower": 367.4539,
          "Upper": 370.3461,
          "x": 1143849600000,
          "low": 367.4539,
          "high": 370.3461
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 382.9,
          "Lower": 381.399,
          "Upper": 384.401,
          "x": 1175385600000,
          "low": 381.399,
          "high": 384.401
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 396.1,
          "Lower": 394.5473,
          "Upper": 397.6527,
          "x": 1207008000000,
          "low": 394.5473,
          "high": 397.6527
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 402.9,
          "Lower": 401.3206,
          "Upper": 404.4794,
          "x": 1238544000000,
          "low": 401.3206,
          "high": 404.4794
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 411.1,
          "Lower": 409.4885,
          "Upper": 412.7115,
          "x": 1270080000000,
          "low": 409.4885,
          "high": 412.7115
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 405.6,
          "Lower": 403.2151,
          "Upper": 407.9849,
          "x": 1301616000000,
          "low": 403.2151,
          "high": 407.9849
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 412.4,
          "Lower": 410.7834,
          "Upper": 414.0166,
          "x": 1333238400000,
          "low": 410.7834,
          "high": 414.0166
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 421.4,
          "Lower": 419.7481,
          "Upper": 423.0519,
          "x": 1364774400000,
          "low": 419.7481,
          "high": 423.0519
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 421.6,
          "Lower": 420.7737,
          "Upper": 422.4263,
          "x": 1396310400000,
          "low": 420.7737,
          "high": 422.4263
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 429,
          "Lower": 426.4775,
          "Upper": 431.5225,
          "x": 1427846400000,
          "low": 426.4775,
          "high": 431.5225
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 442.1,
          "Lower": 440.367,
          "Upper": 443.833,
          "x": 1459468800000,
          "low": 440.367,
          "high": 443.833
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 453.9,
          "Lower": 451.2311,
          "Upper": 456.5689,
          "x": 1491004800000,
          "low": 451.2311,
          "high": 456.5689
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 465.7,
          "Lower": 462.9617,
          "Upper": 468.4383,
          "x": 1522540800000,
          "low": 462.9617,
          "high": 468.4383
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 483,
          "Lower": 480.16,
          "Upper": 485.84,
          "x": 1554076800000,
          "low": 480.16,
          "high": 485.84
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 484.3,
          "Lower": 481.4523,
          "Upper": 487.1477,
          "x": 1585699200000,
          "low": 481.4523,
          "high": 487.1477
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 510,
          "Lower": 508.0008,
          "Upper": 511.9992,
          "x": 1617235200000,
          "low": 508.0008,
          "high": 511.9992
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 536.6,
          "Lower": 535.5483,
          "Upper": 537.6517,
          "x": 1648771200000,
          "low": 535.5483,
          "high": 537.6517
        },
        {
          "Area_name": "England",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 576.9,
          "Lower": 574.6386,
          "Upper": 579.1614,
          "x": 1680307200000,
          "low": 574.6386,
          "high": 579.1614
        }
      ],
      "type": "arearange",
      "linkedTo": "England",
      "opacity": 0.2,
      "enableMouseTracking": false,
      "lineColor": "transparent",
      "showInLegend": false
    },
    {
      "name": "Northern Ireland",
      "data": [
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 284.3,
          "Lower": 273.7127,
          "Upper": 294.8873,
          "x": 1017619200000,
          "low": 273.7127,
          "high": 294.8873
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 290,
          "Lower": 279.2004,
          "Upper": 300.7996,
          "x": 1049155200000,
          "low": 279.2004,
          "high": 300.7996
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 305.4,
          "Lower": 292.8297,
          "Upper": 317.9703,
          "x": 1080777600000,
          "low": 292.8297,
          "high": 317.9703
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 318.7,
          "Lower": 307.4563,
          "Upper": 329.9437,
          "x": 1112313600000,
          "low": 307.4563,
          "high": 329.9437
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 322.8,
          "Lower": 310.7789,
          "Upper": 334.8211,
          "x": 1143849600000,
          "low": 310.7789,
          "high": 334.8211
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 329.6,
          "Lower": 317.9717,
          "Upper": 341.2283,
          "x": 1175385600000,
          "low": 317.9717,
          "high": 341.2283
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 345,
          "Lower": 332.8284,
          "Upper": 357.1716,
          "x": 1207008000000,
          "low": 332.8284,
          "high": 357.1716
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 354.6,
          "Lower": 342.0897,
          "Upper": 367.1103,
          "x": 1238544000000,
          "low": 342.0897,
          "high": 367.1103
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 354.4,
          "Lower": 342.5914,
          "Upper": 366.2086,
          "x": 1270080000000,
          "low": 342.5914,
          "high": 366.2086
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 354.6,
          "Lower": 342.7847,
          "Upper": 366.4153,
          "x": 1301616000000,
          "low": 342.7847,
          "high": 366.4153
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 360.1,
          "Lower": 348.1015,
          "Upper": 372.0985,
          "x": 1333238400000,
          "low": 348.1015,
          "high": 372.0985
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 365.2,
          "Lower": 353.7473,
          "Upper": 376.6527,
          "x": 1364774400000,
          "low": 353.7473,
          "high": 376.6527
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 363.1,
          "Lower": 351.0015,
          "Upper": 375.1985,
          "x": 1396310400000,
          "low": 351.0015,
          "high": 375.1985
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 381.7,
          "Lower": 368.9818,
          "Upper": 394.4182,
          "x": 1427846400000,
          "low": 368.9818,
          "high": 394.4182
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 392.5,
          "Lower": 380.1912,
          "Upper": 404.8088,
          "x": 1459468800000,
          "low": 380.1912,
          "high": 404.8088
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 407.4,
          "Lower": 393.8254,
          "Upper": 420.9746,
          "x": 1491004800000,
          "low": 393.8254,
          "high": 420.9746
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 420.2,
          "Lower": 406.1989,
          "Upper": 434.2011,
          "x": 1522540800000,
          "low": 406.1989,
          "high": 434.2011
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 429.3,
          "Lower": 417.52,
          "Upper": 441.08,
          "x": 1554076800000,
          "low": 417.52,
          "high": 441.08
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 432.7,
          "Lower": 419.1305,
          "Upper": 446.2695,
          "x": 1585699200000,
          "low": 419.1305,
          "high": 446.2695
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 469.5,
          "Lower": 458.4574,
          "Upper": 480.5426,
          "x": 1617235200000,
          "low": 458.4574,
          "high": 480.5426
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 499.2,
          "Lower": 488.4372,
          "Upper": 509.9628,
          "x": 1648771200000,
          "low": 488.4372,
          "high": 509.9628
        },
        {
          "Area_name": "Northern Ireland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 533,
          "Lower": 520.4638,
          "Upper": 545.5362,
          "x": 1680307200000,
          "low": 520.4638,
          "high": 545.5362
        }
      ],
      "type": "arearange",
      "linkedTo": "Northern Ireland",
      "opacity": 0.2,
      "enableMouseTracking": false,
      "lineColor": "transparent",
      "showInLegend": false
    },
    {
      "name": "Scotland",
      "data": [
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 302,
          "Lower": 296.0808,
          "Upper": 307.9192,
          "x": 1017619200000,
          "low": 296.0808,
          "high": 307.9192
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 316.5,
          "Lower": 310.2966,
          "Upper": 322.7034,
          "x": 1049155200000,
          "low": 310.2966,
          "high": 322.7034
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 323.7,
          "Lower": 316.721,
          "Upper": 330.679,
          "x": 1080777600000,
          "low": 316.721,
          "high": 330.679
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 333.4,
          "Lower": 326.8654,
          "Upper": 339.9346,
          "x": 1112313600000,
          "low": 326.8654,
          "high": 339.9346
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 345.5,
          "Lower": 339.4054,
          "Upper": 351.5946,
          "x": 1143849600000,
          "low": 339.4054,
          "high": 351.5946
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 360.2,
          "Lower": 353.1401,
          "Upper": 367.2599,
          "x": 1175385600000,
          "low": 353.1401,
          "high": 367.2599
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 377.2,
          "Lower": 370.5462,
          "Upper": 383.8538,
          "x": 1207008000000,
          "low": 370.5462,
          "high": 383.8538
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 386.4,
          "Lower": 379.5839,
          "Upper": 393.2161,
          "x": 1238544000000,
          "low": 379.5839,
          "high": 393.2161
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 393.3,
          "Lower": 385.5913,
          "Upper": 401.0087,
          "x": 1270080000000,
          "low": 385.5913,
          "high": 401.0087
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 392.7,
          "Lower": 385.0031,
          "Upper": 400.3969,
          "x": 1301616000000,
          "low": 385.0031,
          "high": 400.3969
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 395.9,
          "Lower": 389.6923,
          "Upper": 402.1077,
          "x": 1333238400000,
          "low": 389.6923,
          "high": 402.1077
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 409.3,
          "Lower": 402.0799,
          "Upper": 416.5201,
          "x": 1364774400000,
          "low": 402.0799,
          "high": 416.5201
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 413.7,
          "Lower": 405.5915,
          "Upper": 421.8085,
          "x": 1396310400000,
          "low": 405.5915,
          "high": 421.8085
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 423.6,
          "Lower": 416.1277,
          "Upper": 431.0723,
          "x": 1427846400000,
          "low": 416.1277,
          "high": 431.0723
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 433.2,
          "Lower": 425.5584,
          "Upper": 440.8416,
          "x": 1459468800000,
          "low": 425.5584,
          "high": 440.8416
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 441.4,
          "Lower": 434.4788,
          "Upper": 448.3212,
          "x": 1491004800000,
          "low": 434.4788,
          "high": 448.3212
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 452.6,
          "Lower": 444.6161,
          "Upper": 460.5839,
          "x": 1522540800000,
          "low": 444.6161,
          "high": 460.5839
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 472.8,
          "Lower": 465.3865,
          "Upper": 480.2135,
          "x": 1554076800000,
          "low": 465.3865,
          "high": 480.2135
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 487,
          "Lower": 478.4093,
          "Upper": 495.5907,
          "x": 1585699200000,
          "low": 478.4093,
          "high": 495.5907
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 504.7,
          "Lower": 495.7971,
          "Upper": 513.6029,
          "x": 1617235200000,
          "low": 495.7971,
          "high": 513.6029
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 528.6,
          "Lower": 520.3116,
          "Upper": 536.8884,
          "x": 1648771200000,
          "low": 520.3116,
          "high": 536.8884
        },
        {
          "Area_name": "Scotland",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 588,
          "Lower": 575.3227,
          "Upper": 600.6773,
          "x": 1680307200000,
          "low": 575.3227,
          "high": 600.6773
        }
      ],
      "type": "arearange",
      "linkedTo": "Scotland",
      "opacity": 0.2,
      "enableMouseTracking": false,
      "lineColor": "transparent",
      "showInLegend": false
    },
    {
      "name": "Wales",
      "data": [
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2002-04-01",
          "Year": 2002,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 290.5,
          "Lower": 281.3899,
          "Upper": 299.6101,
          "x": 1017619200000,
          "low": 281.3899,
          "high": 299.6101
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2003-04-01",
          "Year": 2003,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 300.3,
          "Lower": 292.0598,
          "Upper": 308.5402,
          "x": 1049155200000,
          "low": 292.0598,
          "high": 308.5402
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2004-04-01",
          "Year": 2004,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 317,
          "Lower": 307.6802,
          "Upper": 326.3198,
          "x": 1080777600000,
          "low": 307.6802,
          "high": 326.3198
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2005-04-01",
          "Year": 2005,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 320.6,
          "Lower": 311.8027,
          "Upper": 329.3973,
          "x": 1112313600000,
          "low": 311.8027,
          "high": 329.3973
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2006-04-01",
          "Year": 2006,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 334.5,
          "Lower": 325.3213,
          "Upper": 343.6787,
          "x": 1143849600000,
          "low": 325.3213,
          "high": 343.6787
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2007-04-01",
          "Year": 2007,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 337.5,
          "Lower": 328.239,
          "Upper": 346.761,
          "x": 1175385600000,
          "low": 328.239,
          "high": 346.761
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2008-04-01",
          "Year": 2008,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 347.6,
          "Lower": 338.0619,
          "Upper": 357.1381,
          "x": 1207008000000,
          "low": 338.0619,
          "high": 357.1381
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2009-04-01",
          "Year": 2009,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 361.4,
          "Lower": 352.1915,
          "Upper": 370.6085,
          "x": 1238544000000,
          "low": 352.1915,
          "high": 370.6085
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2010-04-01",
          "Year": 2010,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 369.1,
          "Lower": 358.2485,
          "Upper": 379.9515,
          "x": 1270080000000,
          "low": 358.2485,
          "high": 379.9515
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2011-04-01",
          "Year": 2011,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 366.5,
          "Lower": 357.8799,
          "Upper": 375.1201,
          "x": 1301616000000,
          "low": 357.8799,
          "high": 375.1201
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2012-04-01",
          "Year": 2012,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 366.5,
          "Lower": 357.8799,
          "Upper": 375.1201,
          "x": 1333238400000,
          "low": 357.8799,
          "high": 375.1201
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2013-04-01",
          "Year": 2013,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 381.1,
          "Lower": 369.1487,
          "Upper": 393.0513,
          "x": 1364774400000,
          "low": 369.1487,
          "high": 393.0513
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2014-04-01",
          "Year": 2014,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 383.3,
          "Lower": 372.7822,
          "Upper": 393.8178,
          "x": 1396310400000,
          "low": 372.7822,
          "high": 393.8178
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2015-04-01",
          "Year": 2015,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 388.1,
          "Lower": 378.2112,
          "Upper": 397.9888,
          "x": 1427846400000,
          "low": 378.2112,
          "high": 397.9888
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2016-04-01",
          "Year": 2016,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 408,
          "Lower": 398.4038,
          "Upper": 417.5962,
          "x": 1459468800000,
          "low": 398.4038,
          "high": 417.5962
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2017-04-01",
          "Year": 2017,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 412.1,
          "Lower": 402.4074,
          "Upper": 421.7926,
          "x": 1491004800000,
          "low": 402.4074,
          "high": 421.7926
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2018-04-01",
          "Year": 2018,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 422.5,
          "Lower": 411.7347,
          "Upper": 433.2653,
          "x": 1522540800000,
          "low": 411.7347,
          "high": 433.2653
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2019-04-01",
          "Year": 2019,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 446.2,
          "Lower": 436.5799,
          "Upper": 455.8201,
          "x": 1554076800000,
          "low": 436.5799,
          "high": 455.8201
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2020-04-01",
          "Year": 2020,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 455.1,
          "Lower": 442.6121,
          "Upper": 467.5879,
          "x": 1585699200000,
          "low": 442.6121,
          "high": 467.5879
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2021-04-01",
          "Year": 2021,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 470.4,
          "Lower": 461.1802,
          "Upper": 479.6198,
          "x": 1617235200000,
          "low": 461.1802,
          "high": 479.6198
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2022-04-01",
          "Year": 2022,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 505.9,
          "Lower": 494.9928,
          "Upper": 516.8072,
          "x": 1648771200000,
          "low": 494.9928,
          "high": 516.8072
        },
        {
          "Area_name": "Wales",
          "Area_type": "Country",
          "Region": null,
          "Subject": "Labour market",
          "Measure": "Median weekly employee earnings",
          "TimePeriod": "2023-04-01",
          "Year": 2023,
          "Month": 4,
          "Sex": "All",
          "Age": "All",
          "CTBand": "All",
          "Data": 540,
          "Lower": 527.2992,
          "Upper": 552.7008,
          "x": 1680307200000,
          "low": 527.2992,
          "high": 552.7008
        }
      ],
      "type": "arearange",
      "linkedTo": "Wales",
      "opacity": 0.2,
      "enableMouseTracking": false,
      "lineColor": "transparent",
      "showInLegend": false
    }
  ],
  "xAxis": {
    "type": "datetime"
  },
  "colors": ["#500778", "#003057", "#007DBA", "#00A9E0"],
  "tooltip": {
    "valueDecimals": 0,
    "valuePrefix": "£",
    "xDateFormat": "%b %Y"
  },
  "legend": {
    "verticalAlign": "top",
    "align": "right",
    "floating": true,
    "backgroundColor": "white",
    "y": 20
  }
}
